<?php
// $Id: xoops_version.php,v 1.13 2003/04/01 22:51:21 mvandam Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = _MI_SERVER_NAME;
$modversion['version'] = 0.53;
$modversion['description'] = _MI_SERVER_DESC;
$modversion['credits'] = "The XOOPS Project";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['author'] = "Mithrandir";
$modversion['image'] = "images/server_slogo.png";
$modversion['dirname'] = "serverbooking";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "server_bookings";
$modversion['tables'][1] = "server_serveradmins";
$modversion['tables'][2] = "server_bookers";
$modversion['tables'][3] = "server_rules";
$modversion['tables'][4] = "server_preferences";
$modversion['tables'][5] = "server_scrimm";
$modversion['tables'][6] = "server_serverprefs";
$modversion['tables'][7] = "server_team";
$modversion['tables'][8] = "server_teamadmins";
$modversion['tables'][9] = "server_teamprefs";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "bookings.php";
$modversion['blocks'][1]['name'] = _MI_SERVER_BNAME1;
$modversion['blocks'][1]['description'] = "Shows Bookings";
$modversion['blocks'][1]['show_func'] = "sh_bookings";

$modversion['blocks'][2]['file'] = "top_bookers.php";
$modversion['blocks'][2]['name'] = _MI_SERVER_BNAME2;
$modversion['blocks'][2]['description'] = "Shows Top Bookers";
$modversion['blocks'][2]['show_func'] = "b_bookers_show";
$modversion['blocks'][2]['edit_func'] = "b_bookers_edit";
$modversion['blocks'][2]['options'] = "5|Bookings|30";

$modversion['blocks'][3]['file'] = "top_servers.php";
$modversion['blocks'][3]['name'] = _MI_SERVER_BNAME3;
$modversion['blocks'][3]['description'] = "Shows Top Servers";
$modversion['blocks'][3]['show_func'] = "b_servers_show";
$modversion['blocks'][3]['edit_func'] = "b_servers_edit";
$modversion['blocks'][3]['options'] = "5|Bookings|30";

$modversion['blocks'][4]['file'] = "navigation.php";
$modversion['blocks'][4]['name'] = _MI_SERVER_BNAME4;
$modversion['blocks'][4]['description'] = "Module Navigation";
$modversion['blocks'][4]['show_func'] = "sh_nav";


// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_SEARCH;
$modversion['sub'][1]['url'] = "search.php";
$modversion['sub'][2]['name'] = _MI_SERVER_SMNAME3;
$modversion['sub'][2]['url'] = "BookMatch.php";

global $xoopsModule;
if ($modversion['dirname'] == $xoopsModule->getVar('dirname')) {
    include_once 'specialfunctions.php';
    global $xoopsUser;
    if ($xoopsUser) {
        $modversion['sub'][] = array('name'=> _MI_SIGNUPSERVER,
        'url' => 'server.php');
        $servers = getAdminServers($xoopsUser->getVar('uid'));
        $serverlink = '?zone='.$xoopsUser->timezone();
        foreach ($servers as $sid => $sname) {
            $serverlink .= '&serverid[]='.$sid;
            $modversion['sub'][] = array('name' => _MI_MANAGE.' '.$sname,
            'url' => 'serveradmin.php?serverid='.$sid);
        }
        $modversion['sub'][] = array('name' => _MI_MYSERVERS,
        'url' => 'index.php'.$serverlink);
    }
}
//$modversion['sub'][] = array('name' => _MI_SB_QUERY, 'url' => 'query.php');

// Config Settings (only for modules that need config settings generated automatically)

// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'confirmationmail';

// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_MI_SERVER_CONFMAIL';

// description of this config option displayed under title
$modversion['config'][1]['description'] = '_MI_SERVER_CONFMAILDESC';

// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'yesno';

// value type of this config option. can be one of either int, text, float, array, or other
// form type of group_multi, select_multi must always be value type of array
$modversion['config'][1]['valuetype'] = 'int';

// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = 0;

$modversion['config'][2]['name'] = 'serveremail';
$modversion['config'][2]['title'] = '_MI_SERVER_MAIL';
$modversion['config'][2]['description'] = '_MI_SERVER_MAILDESC';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = 'booking@thissite.com';

$modversion['config'][3]['name'] = 'defview';
$modversion['config'][3]['title'] = '_MI_SERVER_DEFVIEW';
$modversion['config'][3]['description'] = '';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = '1';
$modversion['config'][3]['options'] = array('Month' => '1', 'Week' => '2');

$modversion['config'][4]['name'] = 'serveradminmail';
$modversion['config'][4]['title'] = '_MI_SERVERADMIN_CONFMAIL';
$modversion['config'][4]['description'] = '_MI_SERVERADMIN_CONFMAILDESC';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['templates'][1]['file'] = 'server_select.html';
$modversion['templates'][1]['description'] = 'Select box for server selection';
$modversion['templates'][2]['file'] = 'serverbooking_month.html';
$modversion['templates'][2]['description'] = 'Monthly booking display';
$modversion['templates'][3]['file'] = 'serverbooking_week.html';
$modversion['templates'][3]['description'] = 'Weekly booking display';
$modversion['templates'][4]['file'] = 'serverbooking_query.html';
$modversion['templates'][4]['description'] = 'Server Querying';
$modversion['templates'][5]['file'] = 'server_viewscrimm.html';
$modversion['templates'][5]['description'] = 'Scrimm details';
$modversion['templates'][6]['file'] = 'server_scrimmlist.html';
$modversion['templates'][6]['description'] = 'Scrimm Listing';
$modversion['templates'][7]['file'] = 'server_teamlist.html';
$modversion['templates'][7]['description'] = 'Team Listing';

$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'viewscrimm.php';
$modversion['comments']['itemName'] = 'scrimmid';

//$modversion['comments']['callbackFile'] = 'include/comment_functions.php';

$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'scrimm_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_SERVER_SCRIMM_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_SERVER_SCRIMM_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = 'scrimms.php';

$modversion['notification']['category'][2]['name'] = 'scrimm';
$modversion['notification']['category'][2]['title'] = _MI_SERVER_REPLY_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_SERVER_REPLY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = 'viewscrimm.php';
$modversion['notification']['category'][2]['item_name'] = 'scrimmid';

$modversion['notification']['event'][1]['name'] = 'new_scrimm';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_SERVER_NEWSCRIMM_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_SERVER_NEWSCRIMM_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_SERVER_NEWSCRIMM_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'server_newscrimm_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_SERVER_NEWSCRIMM_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'new_reply';
$modversion['notification']['event'][2]['category'] = 'scrimm';
$modversion['notification']['event'][2]['title'] = _MI_SERVER_NEWREPLY_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_SERVER_NEWREPLY_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_SERVER_NEWREPLY_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'scrimm_newreply_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_SERVER_NEWREPLY_NOTIFYSBJ;
?>